// CSS-in-JS via real `styled-components`: styles are defined AS JavaScript,
// colocated with the component, and scoped class names are generated at
// RUNTIME (unlike CSS Modules' build-time hashing) based on the styles'
// own content. Plain React.createElement is used instead of JSX, so this
// runs directly with `node`, no build step/Babel required.
import React from 'react';
import { renderToString } from 'react-dom/server';
import { styled, ServerStyleSheet } from 'styled-components';

const Alert = styled.div`
  border-radius: 8px;
  padding: 16px;
  border: 1px solid transparent;
  background: ${(props) => (props.$variant === 'success' ? '#dcfce7' : '#fee2e2')};
  border-color: ${(props) => (props.$variant === 'success' ? '#16a34a' : '#dc2626')};
  color: ${(props) => (props.$variant === 'success' ? '#14532d' : '#7f1d1d')};
`;

const Title = styled.p`
  font-weight: 700;
  margin: 0 0 4px 0;
`;

// A completely UNRELATED component, ALSO using a styled `Title`-shaped
// element with the exact same conceptual role -- proving styled-components'
// generated class names don't collide, the same core proof CSS Modules made
// at build time, here happening at JS runtime instead.
const CardTitle = styled.p`
  font-size: 1.1rem;
  color: #4f46e5;
`;

const sheet = new ServerStyleSheet();
const html = renderToString(
  sheet.collectStyles(
    React.createElement(
      'div',
      null,
      React.createElement(
        Alert,
        { '$variant': 'success' },
        React.createElement(Title, null, 'Success (Alert-scoped Title)'),
        React.createElement('p', null, 'Your changes were saved.'),
      ),
      React.createElement(
        'div',
        { style: { marginTop: '16px', border: '1px solid #e5e7eb', borderRadius: '8px', padding: '16px' } },
        React.createElement(CardTitle, null, 'A Card (its OWN, differently-scoped Title)'),
      ),
    ),
  ),
);

const styleTags = sheet.getStyleTags();
sheet.seal();

console.log('=== Rendered HTML (real class names generated by styled-components AT RUNTIME) ===');
console.log(html);

console.log('\n=== Generated <style> tags ===');
console.log(styleTags);

// Extract the two distinct generated class names actually used in the HTML,
// to directly prove they're different despite both components conceptually
// being "a bold/colored title text."
//
// A real bug caught while writing this check: a first version compared
// classMatches[1] against classMatches[3] on the assumption there were 4
// class-bearing elements in the rendered HTML -- there are only 3 (the
// plain, unstyled <p> tags never get a class="..." attribute at all), so
// classMatches[3] was actually `undefined`. The comparison still printed
// "true", but only by accident (anything !== undefined is true) -- not
// because it was actually comparing the two Title elements' real classes.
// Fixed by matching each element BY NAME instead of by a guessed index.
const classMatches = [...html.matchAll(/class="([^"]+)"/g)].map((m) => m[1]);
console.log('\n=== Classes found in the rendered HTML ===');
console.log(classMatches);

const [alertClass, alertTitleClass, cardTitleClass] = classMatches;
console.log('Alert div class:', alertClass);
console.log('Alert-scoped Title class:', alertTitleClass);
console.log('Card-scoped Title class:', cardTitleClass);
console.log('Alert-scoped Title class differs from Card-scoped Title class:',
  alertTitleClass !== cardTitleClass);
