spring.application.name=orderservice

spring.datasource.url=jdbc:h2:mem:orderservice;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

server.port=8083

inventory.base-url=http://localhost:8082
inventory.api-key=inventory-internal-secret-key
