name:                 testing-demo
version:              0.1.0.0
visibility:           public
id:                   testing-demo-0.1.0.0-inplace
key:                  testing-demo-0.1.0.0-inplace
abi:                  inplace
exposed:              True
exposed-modules:      Calculator
import-dirs:
    C:\Users\HP\Complete-Programming-Mastery\01-Languages\Haskell\18-Testing\testing-demo\dist-newstyle\build\x86_64-windows\ghc-9.8.2\testing-demo-0.1.0.0\build

library-dirs:
    C:\Users\HP\Complete-Programming-Mastery\01-Languages\Haskell\18-Testing\testing-demo\dist-newstyle\build\x86_64-windows\ghc-9.8.2\testing-demo-0.1.0.0\build

library-dirs-static:
    C:\Users\HP\Complete-Programming-Mastery\01-Languages\Haskell\18-Testing\testing-demo\dist-newstyle\build\x86_64-windows\ghc-9.8.2\testing-demo-0.1.0.0\build

dynamic-library-dirs:
    C:\Users\HP\Complete-Programming-Mastery\01-Languages\Haskell\18-Testing\testing-demo\dist-newstyle\build\x86_64-windows\ghc-9.8.2\testing-demo-0.1.0.0\build

data-dir:
    C:\Users\HP\Complete-Programming-Mastery\01-Languages\Haskell\18-Testing\testing-demo\.

hs-libraries:         HStesting-demo-0.1.0.0-inplace
depends:              base-4.19.1.0-6554
haddock-interfaces:
    C:\Users\HP\Complete-Programming-Mastery\01-Languages\Haskell\18-Testing\testing-demo\dist-newstyle\build\x86_64-windows\ghc-9.8.2\testing-demo-0.1.0.0\doc\html\testing-demo\testing-demo.haddock

haddock-html:
    C:\Users\HP\Complete-Programming-Mastery\01-Languages\Haskell\18-Testing\testing-demo\dist-newstyle\build\x86_64-windows\ghc-9.8.2\testing-demo-0.1.0.0\doc\html\testing-demo
