package com.example.taskapi;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

/**
 * The SAME public API shape as Lesson 02's controller, but now backed by a REAL,
 * persisted database via TaskRepository instead of an in-memory Map -- the whole
 * point of this lesson: swapping storage from memory to a genuine database changed
 * NOTHING about the controller's external behavior, only how it talks to storage.
 */
@RestController
@RequestMapping("/tasks")
public class TaskController {

    private final TaskRepository repository;

    public TaskController(TaskRepository repository) { // constructor injection -- Spring supplies this automatically
        this.repository = repository;
    }

    @GetMapping
    public List<Task> listTasks() {
        return repository.findAll(); // a REAL "SELECT * FROM task" query, generated by Spring Data
    }

    @GetMapping("/pending")
    public List<Task> listPendingTasks() {
        return repository.findByDoneFalse(); // the derived query from TaskRepository
    }

    @GetMapping("/{id}")
    public ResponseEntity<Task> getTask(@PathVariable Long id) {
        return repository.findById(id)
                .map(ResponseEntity::ok)
                .orElseGet(() -> ResponseEntity.notFound().build());
    }

    @PostMapping
    public ResponseEntity<Task> createTask(@RequestBody NewTaskRequest request) {
        if (request.title() == null || request.title().isBlank()) {
            return ResponseEntity.badRequest().build();
        }
        Task saved = repository.save(new Task(request.title(), false)); // INSERT, id assigned by the DB
        return ResponseEntity.status(HttpStatus.CREATED).body(saved);
    }

    @PutMapping("/{id}")
    public ResponseEntity<Task> updateTask(@PathVariable Long id, @RequestBody NewTaskRequest request) {
        return repository.findById(id)
                .map(task -> {
                    task.setTitle(request.title());
                    return ResponseEntity.ok(repository.save(task)); // UPDATE, since the id already exists
                })
                .orElseGet(() -> ResponseEntity.notFound().build());
    }

    @PatchMapping("/{id}/complete")
    public ResponseEntity<Task> completeTask(@PathVariable Long id) {
        return repository.findById(id)
                .map(task -> {
                    task.setDone(true);
                    return ResponseEntity.ok(repository.save(task));
                })
                .orElseGet(() -> ResponseEntity.notFound().build());
    }

    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteTask(@PathVariable Long id) {
        if (!repository.existsById(id)) {
            return ResponseEntity.notFound().build();
        }
        repository.deleteById(id);
        return ResponseEntity.noContent().build();
    }
}
